### ISSUE TITLE
How to get NDEF records?

### ISSUE THREAD

**Issue by devcassa1** [mitchjacksontech/TagReader#1]

**Comment by mitchjacksontech** [comment]
This library only reads the UID of the rfid tag when it is detected near the reader.

It does this using `GetCardIdEx()` seen [here](https://github.com/mitchjacksontech/TagReader/blob/cfab14c85562bf941cec45cdb9fe08d795ba0477/TagReader.py#L42) in the `poll_tags` method.

You could expand on this to use other features available from the ufr C API. Such as `get_ndef_record_count()`, `read_ndef_record()`, `write_ndef_record()`, etc. See the [uFR C api documentation](https://www.d-logic.com/storage/2020/08/uFR_Series_NFC_reader_API.pdf) (this may not be the latest docs, I did not spend much time searching.)

This code interacts with the uFR C system library's API with `ctypes` `CDLL` features. You can see examples of how that works in the codebase, and find documentation for how this works in python [here](https://docs.python.org/3/library/ctypes.html)

Good luck!
